In [1]:
# using JSON file for my api_key

# Need to import json to do this
# Need to requests 
# Need to pandas for dataframe
import json
import requests
import pandas as pd

# Define a function for openning the json
def get_keys(path):
    with open(path) as f:
        return json.load(f)

# Using the function to open and load all keys in that file 
api_keys = get_keys("/Users/ezgi/.secret_the_movie/movie_api.json")

# Setting the first (and only) value as a variable
ds_key_1 = list(api_keys.values())[0]

In [2]:
# url = f"https://api.themoviedb.org/3/movie/550?api_key={ds_key_1}"  for movie id

In [3]:
url = f'https://api.themoviedb.org/3/discover/movie?api_key={ds_key_1}&primary_release_year=2019&sort_by=revenue.desc'
# for yearly highest revenue for 2019

In [4]:
# url = f'https://api.themoviedb.org/3/discover/movie/?api_key={ds_key_1}&certification_country=US&certification=R&sort_by=vote_average.desc'
# for vote avg

In [5]:
# url = f"https://api.themoviedb.org/3/movie/top_rated?api_key={ds_key_1}&language=en-US&page=1"
# for top rates films

In [6]:
ds_r = requests.get(url)

In [7]:
ds_r.json().keys()

dict_keys(['page', 'total_results', 'total_pages', 'results'])

In [8]:
# ds_r.json()['results']

In [9]:
"""for key in ds_r.json().keys():
    print(key)
    value = ds_r.json()[key] #Use standard dictionary formatting
    print(value) #What type is it?
    print('\n\n') #Separate out data"""

"for key in ds_r.json().keys():\n    print(key)\n    value = ds_r.json()[key] #Use standard dictionary formatting\n    print(value) #What type is it?\n    print('\n\n') #Separate out data"

In [10]:
for key in ds_r.json().keys():
    print(key)
    value = ds_r.json()[key] #Use standard dictionary formatting
    print(type(value)) #What type is it?
    print('\n\n') #Separate out data

page
<class 'int'>



total_results
<class 'int'>



total_pages
<class 'int'>



results
<class 'list'>

In [11]:
df = pd.DataFrame.from_dict(ds_r.json()['results'])
print(len(df)) #Print how many rows
print(df.columns) #Print column names
df

20
Index(['popularity', 'vote_count', 'video', 'poster_path', 'id', 'adult',
       'backdrop_path', 'original_language', 'original_title', 'genre_ids',
       'title', 'vote_average', 'overview', 'release_date'],
      dtype='object')

,popularity,vote_count,video,poster_path,id,adult,backdrop_path,original_language,original_title,genre_ids,title,vote_average,overview,release_date
0,39.839,11378,False,/or06FN3Dka5tukK1e9sl16pB3iy.jpg,299534,False,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,en,Avengers: Endgame,"[28, 12, 878]",Avengers: Endgame,8.3,After the devastating events of Avengers: Infi...,2019-04-24
1,47.264,4577,False,/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg,420818,False,/nRXO2SnOA75OsWhNhXstHB8ZmI3.jpg,en,The Lion King,"[12, 10751]",The Lion King,7.1,"Simba idolizes his father, King Mufasa, and ta...",2019-07-12
2,127.227,2591,False,/pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg,330457,False,/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg,en,Frozen II,"[12, 16, 10751]",Frozen II,7.0,"Elsa, Anna, Kristoff and Olaf head far into th...",2019-11-20
3,52.388,6121,False,/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg,429617,False,/5myQbDzw3l8K9yofUXRJ4UTVgam.jpg,en,Spider-Man: Far from Home,"[28, 12, 878]",Spider-Man: Far from Home,7.5,Peter Parker and his friends go on a summer tr...,2019-06-28
4,40.323,8387,False,/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg,299537,False,/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg,en,Captain Marvel,"[28, 12, 878]",Captain Marvel,7.0,The story follows Carol Danvers as she becomes...,2019-03-06
5,98.211,9521,False,/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg,475557,False,/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg,en,Joker,"[80, 18, 53]",Joker,8.2,"During the 1980s, a failed stand-up comedian i...",2019-10-02
6,34.046,3771,False,/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg,301528,False,/m67smI1IIMmYzCl9axvKNULVKLr.jpg,en,Toy Story 4,"[12, 16, 35, 14, 10751]",Toy Story 4,7.5,Woody has always been confident about his plac...,2019-06-19
7,54.990,3051,False,/db32LaOibwEliAmSL2jjDF6oDdj.jpg,181812,False,/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg,en,Star Wars: The Rise of Skywalker,"[28, 12, 878]",Star Wars: The Rise of Skywalker,6.5,The surviving Resistance faces the First Order...,2019-12-18
8,48.212,4927,False,/3iYQTLGoy7QnjcUYRJy4YrAgGvp.jpg,420817,False,/rVqY0Bo4Npf6EIONUROxjYAJfmD.jpg,en,Aladdin,"[12, 35, 14, 10749, 10751]",Aladdin,7.0,A kindhearted street urchin named Aladdin emba...,2019-05-22
9,42.665,2620,False,/kvpNZAQow5es1tSY6XW2jAZuPPG.jpg,384018,False,/qAhedRxRYWZAgZ8O8pHIl6QHdD7.jpg,en,Fast & Furious Presents: Hobbs & Shaw,"[28, 12, 35]",Fast & Furious Presents: Hobbs & Shaw,6.6,Ever since US Diplomatic Security Service Agen...,2019-08-01
10,23.493,30,False,/phM9bb6s9c60LA8qwsdk7U1N2cS.jpg,615453,False,/58W0GbpzJlOC0Mce9R2N4ZSG97w.jpg,zh,哪吒之魔童降世,"[16, 35, 14]",Ne Zha,7.4,The Primus extracts a Mixed Yuan Bead into a S...,2019-07-26
11,34.495,3086,False,/xvx4Yhf0DVH8G4LzNISpMfFBDy2.jpg,166428,False,/lFwykSz3Ykj1Q3JXJURnGUTNf1o.jpg,en,How to Train Your Dragon: The Hidden World,"[12, 16, 10751]",How to Train Your Dragon: The Hidden World,7.7,As Hiccup fulfills his dream of creating a pea...,2019-01-03
12,51.865,1961,False,/vloNTScJ3w7jwNwtNGoG8DbTThv.jpg,420809,False,/skvI4rYFrKXS73BJxWGH54Omlvv.jpg,en,Maleficent: Mistress of Evil,"[12, 14, 10751]",Maleficent: Mistress of Evil,7.2,Maleficent and her goddaughter Aurora begin to...,2019-10-16
13,33.304,3245,False,/zfE0R94v1E8cuKAerbskfD3VfUt.jpg,474350,False,/8moTOzunF7p40oR5XhlDvJckOSW.jpg,en,It Chapter Two,"[18, 14, 27]",It Chapter Two,6.8,27 years after overcoming the malevolent super...,2019-09-04
14,32.167,3248,False,/wgQ7APnFpf1TuviKHXeEe3KnsTV.jpg,447404,False,/nDP33LmQwNsnPv29GQazz59HjJI.jpg,en,Pokémon Detective Pikachu,"[28, 12, 14]",Pokémon Detective Pikachu,6.9,In a world where people collect pocket-size mo...,2019-05-03
15,35.214,4329,False,/xRWht48C2V8XNfzvPehyClOvDni.jpg,399579,False,/8RKBHHRqOMOLh5qW3sS6TSFTd8h.jpg,en,Alita: Battle Angel,"[28, 12, 878, 53]",Alita: Battle Angel,6.9,When Alita awakens with no memory of who she i...,2019-01-31
16,32.712,2107,False,/pU3bnutJU91u3b4IeRPQTOP8jhV.jpg,373571,False,/cNt14e43I2DDW6Xd9zFhrP8eOcA.jpg,en,Godzilla: King of the Monsters,"[878, 28]",Godzilla: King of the Monsters,6.2,Follows the heroic efforts of the crypto-zoolo...,2019-05-29
17,55.335,4841,False,/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg,466272,False,/er1S5nJyDSkmy7i2KkPMBjbwK8x.jpg,en,Once Upon a Time… in Hollywood,"[35, 18, 53]",Once Upon a Time… in Hollywood,7.5,"Los Angeles, 1969. TV star Rick Dalton, a stru...",2019-07-25
18,30.909,4374,False,/xnopI5Xtky18MPhK40cZAGAOVeV.jpg,287947,False,/OIGX2lm5tmlCKvZUghtwHzoxxO.jpg,en,Shazam!,"[28, 35, 14]",Shazam!,7.0,A boy is given the ability to become an adult ...,2019-03-29
19,44.085,3943,False,/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg,458156,False,/stemLQMLDrlpfIlZ5OjllOPT8QX.jpg,en,John Wick: Chapter 3 - Parabellum,"[28, 80, 53]",John Wick: Chapter 3 - Parabellum,7.1,Super-assassin John Wick returns with a $14 mi...,2019-05-15

In [12]:
highest_revenue = ds_r.json() # store parsed json response

# uncomment the next line to get a peek at the highest_revenue json structure
# highest_revenue

highest_revenue_films = highest_revenue['results']

In [13]:
columns = ['id','film', 'revenue','genres','vote_count','vote_average','release_date','original_language',
           'orijinal_title','popularity']


# create dataframe with film and revenue columns
df_1= pd.DataFrame(columns=columns)

In [14]:
for film in highest_revenue_films:
    # print(film['title'])
    film_revenue = requests.get('https://api.themoviedb.org/3/movie/'+ str(film['id']) +'?api_key='+ ds_key_1+'&language=en-US')
    film_revenue = film_revenue.json()
    #print(locale.currency(film_revenue['revenue'], grouping=True ))
    df_1.loc[len(df_1)]=[film['id'],film['title'],film_revenue['revenue'],film['genre_ids'],film['vote_count'],
                         film['vote_average'],film['release_date'],film['original_language'],film['original_title'],
                          film['popularity']]


# create dataframe with film and revenue columns
df_1

,id,film,revenue,genres,vote_count,vote_average,release_date,original_language,orijinal_title,popularity
0,299534,Avengers: Endgame,2797800564,"[28, 12, 878]",11378,8.3,2019-04-24,en,Avengers: Endgame,39.839
1,420818,The Lion King,1656943394,"[12, 10751]",4577,7.1,2019-07-12,en,The Lion King,47.264
2,330457,Frozen II,1330764959,"[12, 16, 10751]",2591,7.0,2019-11-20,en,Frozen II,127.227
3,429617,Spider-Man: Far from Home,1131450163,"[28, 12, 878]",6121,7.5,2019-06-28,en,Spider-Man: Far from Home,52.388
4,299537,Captain Marvel,1128274794,"[28, 12, 878]",8387,7.0,2019-03-06,en,Captain Marvel,40.323
5,475557,Joker,1073698955,"[80, 18, 53]",9521,8.2,2019-10-02,en,Joker,98.211
6,301528,Toy Story 4,1073394593,"[12, 16, 35, 14, 10751]",3771,7.5,2019-06-19,en,Toy Story 4,34.046
7,181812,Star Wars: The Rise of Skywalker,1058056021,"[28, 12, 878]",3051,6.5,2019-12-18,en,Star Wars: The Rise of Skywalker,54.990
8,420817,Aladdin,1047612394,"[12, 35, 14, 10749, 10751]",4927,7.0,2019-05-22,en,Aladdin,48.212
9,384018,Fast & Furious Presents: Hobbs & Shaw,760098996,"[28, 12, 35]",2620,6.6,2019-08-01,en,Fast & Furious Presents: Hobbs & Shaw,42.665
10,615453,Ne Zha,686067000,"[16, 35, 14]",30,7.4,2019-07-26,zh,哪吒之魔童降世,23.493
11,166428,How to Train Your Dragon: The Hidden World,517526875,"[12, 16, 10751]",3086,7.7,2019-01-03,en,How to Train Your Dragon: The Hidden World,34.495
12,420809,Maleficent: Mistress of Evil,491570967,"[12, 14, 10751]",1961,7.2,2019-10-16,en,Maleficent: Mistress of Evil,51.865
13,474350,It Chapter Two,472093228,"[18, 14, 27]",3245,6.8,2019-09-04,en,It Chapter Two,33.304
14,447404,Pokémon Detective Pikachu,431605346,"[28, 12, 14]",3248,6.9,2019-05-03,en,Pokémon Detective Pikachu,32.167
15,399579,Alita: Battle Angel,404852543,"[28, 12, 878, 53]",4329,6.9,2019-01-31,en,Alita: Battle Angel,35.214
16,373571,Godzilla: King of the Monsters,385900138,"[878, 28]",2107,6.2,2019-05-29,en,Godzilla: King of the Monsters,32.712
17,466272,Once Upon a Time… in Hollywood,374251247,"[35, 18, 53]",4841,7.5,2019-07-25,en,Once Upon a Time… in Hollywood,55.335
18,287947,Shazam!,363533271,"[28, 35, 14]",4374,7.0,2019-03-29,en,Shazam!,30.909
19,458156,John Wick: Chapter 3 - Parabellum,326699296,"[28, 80, 53]",3943,7.1,2019-05-15,en,John Wick: Chapter 3 - Parabellum,44.085

In [15]:
df_1

,id,film,revenue,genres,vote_count,vote_average,release_date,original_language,orijinal_title,popularity
0,299534,Avengers: Endgame,2797800564,"[28, 12, 878]",11378,8.3,2019-04-24,en,Avengers: Endgame,39.839
1,420818,The Lion King,1656943394,"[12, 10751]",4577,7.1,2019-07-12,en,The Lion King,47.264
2,330457,Frozen II,1330764959,"[12, 16, 10751]",2591,7.0,2019-11-20,en,Frozen II,127.227
3,429617,Spider-Man: Far from Home,1131450163,"[28, 12, 878]",6121,7.5,2019-06-28,en,Spider-Man: Far from Home,52.388
4,299537,Captain Marvel,1128274794,"[28, 12, 878]",8387,7.0,2019-03-06,en,Captain Marvel,40.323
5,475557,Joker,1073698955,"[80, 18, 53]",9521,8.2,2019-10-02,en,Joker,98.211
6,301528,Toy Story 4,1073394593,"[12, 16, 35, 14, 10751]",3771,7.5,2019-06-19,en,Toy Story 4,34.046
7,181812,Star Wars: The Rise of Skywalker,1058056021,"[28, 12, 878]",3051,6.5,2019-12-18,en,Star Wars: The Rise of Skywalker,54.990
8,420817,Aladdin,1047612394,"[12, 35, 14, 10749, 10751]",4927,7.0,2019-05-22,en,Aladdin,48.212
9,384018,Fast & Furious Presents: Hobbs & Shaw,760098996,"[28, 12, 35]",2620,6.6,2019-08-01,en,Fast & Furious Presents: Hobbs & Shaw,42.665
10,615453,Ne Zha,686067000,"[16, 35, 14]",30,7.4,2019-07-26,zh,哪吒之魔童降世,23.493
11,166428,How to Train Your Dragon: The Hidden World,517526875,"[12, 16, 10751]",3086,7.7,2019-01-03,en,How to Train Your Dragon: The Hidden World,34.495
12,420809,Maleficent: Mistress of Evil,491570967,"[12, 14, 10751]",1961,7.2,2019-10-16,en,Maleficent: Mistress of Evil,51.865
13,474350,It Chapter Two,472093228,"[18, 14, 27]",3245,6.8,2019-09-04,en,It Chapter Two,33.304
14,447404,Pokémon Detective Pikachu,431605346,"[28, 12, 14]",3248,6.9,2019-05-03,en,Pokémon Detective Pikachu,32.167
15,399579,Alita: Battle Angel,404852543,"[28, 12, 878, 53]",4329,6.9,2019-01-31,en,Alita: Battle Angel,35.214
16,373571,Godzilla: King of the Monsters,385900138,"[878, 28]",2107,6.2,2019-05-29,en,Godzilla: King of the Monsters,32.712
17,466272,Once Upon a Time… in Hollywood,374251247,"[35, 18, 53]",4841,7.5,2019-07-25,en,Once Upon a Time… in Hollywood,55.335
18,287947,Shazam!,363533271,"[28, 35, 14]",4374,7.0,2019-03-29,en,Shazam!,30.909
19,458156,John Wick: Chapter 3 - Parabellum,326699296,"[28, 80, 53]",3943,7.1,2019-05-15,en,John Wick: Chapter 3 - Parabellum,44.085

In [16]:
# for 2018 values
url_2018 = f'https://api.themoviedb.org/3/discover/movie?api_key={ds_key_1}&primary_release_year=2018&sort_by=revenue.desc'

In [17]:
ds_r_2018 = requests.get(url_2018)

df_2018 = pd.DataFrame.from_dict(ds_r_2018.json()['results'])
print(len(df_2018)) #Print how many rows
print(df_2018.columns) #Print column names
# df_2018

20
Index(['popularity', 'vote_count', 'video', 'poster_path', 'id', 'adult',
       'backdrop_path', 'original_language', 'original_title', 'genre_ids',
       'title', 'vote_average', 'overview', 'release_date'],
      dtype='object')

In [18]:
highest_revenue_2018 = ds_r_2018.json()

highest_revenue_films_2018 = highest_revenue_2018['results']

In [19]:
columns_2018 = ['id','film', 'revenue','genres','vote_count','vote_average','release_date','original_language',
           'orijinal_title','popularity']
# create dataframe with film and revenue columns
df_2018= pd.DataFrame(columns=columns_2018)

In [20]:
for film in highest_revenue_films_2018:
    # print(film['title'])
    film_revenue_2018 = requests.get('https://api.themoviedb.org/3/movie/'+ str(film['id']) +'?api_key='+ ds_key_1+'&language=en-US')
    film_revenue_2018 = film_revenue_2018.json()
    #print(locale.currency(film_revenue['revenue'], grouping=True ))
    df_2018.loc[len(df_2018)]=[film['id'],film['title'],film_revenue_2018['revenue'],film['genre_ids'],film['vote_count'],
                         film['vote_average'],film['release_date'],film['original_language'],film['original_title'],
                          film['popularity']]


# create dataframe with film and revenue columns
df_2018.shape

(20, 10)

In [21]:
# for 2017 values
url_2017 = f'https://api.themoviedb.org/3/discover/movie?api_key={ds_key_1}&primary_release_year=2017&sort_by=revenue.desc'

In [22]:
ds_r_2017 = requests.get(url_2017)

df_2017 = pd.DataFrame.from_dict(ds_r_2017.json()['results'])
# print(len(df_2017)) #Print how many rows
# print(df_2017.columns) #Print column names
# df_2017

In [23]:
highest_revenue_2017 = ds_r_2017.json()

highest_revenue_films_2017 = highest_revenue_2017['results']

In [24]:
columns_2017 = ['id','film', 'revenue','genres','vote_count','vote_average','release_date','original_language',
           'orijinal_title','popularity']
#            'popularity'

# create dataframe with film and revenue columns
df_2017= pd.DataFrame(columns=columns_2017)

In [25]:
for film in highest_revenue_films_2017:
    # print(film['title'])
    film_revenue_2017 = requests.get('https://api.themoviedb.org/3/movie/'+ str(film['id']) +'?api_key='+ ds_key_1+'&language=en-US')
    film_revenue_2017 = film_revenue_2017.json()
    #print(locale.currency(film_revenue['revenue'], grouping=True ))
    df_2017.loc[len(df_2017)]=[film['id'],film['title'],film_revenue_2017['revenue'],film['genre_ids'],film['vote_count'],
                         film['vote_average'],film['release_date'],film['original_language'],film['original_title'],
                          film['popularity']]


# create dataframe with film and revenue columns
df_2017.shape

(20, 10)

In [26]:
# For 2016
url_2016 = f'https://api.themoviedb.org/3/discover/movie?api_key={ds_key_1}&primary_release_year=2016&sort_by=revenue.desc'

In [27]:
ds_r_2016 = requests.get(url_2016)

df_2016 = pd.DataFrame.from_dict(ds_r_2016.json()['results'])
# print(len(df_2017)) #Print how many rows
# print(df_2017.columns) #Print column names
# df_2017

In [28]:
highest_revenue_2016 = ds_r_2016.json()

highest_revenue_films_2016 = highest_revenue_2016['results']

In [29]:
columns_2016 = ['id','film', 'revenue','genres','vote_count','vote_average','release_date','original_language',
           'orijinal_title','popularity']


# create dataframe with film and revenue columns
df_2016= pd.DataFrame(columns=columns_2016)

In [30]:
for film in highest_revenue_films_2016:
    # print(film['title'])
    film_revenue_2016 = requests.get('https://api.themoviedb.org/3/movie/'+ str(film['id']) +'?api_key='+ ds_key_1+'&language=en-US')
    film_revenue_2016 = film_revenue_2016.json()
    #print(locale.currency(film_revenue['revenue'], grouping=True ))
    df_2016.loc[len(df_2016)]=[film['id'],film['title'],film_revenue_2016['revenue'],film['genre_ids'],film['vote_count'],
                         film['vote_average'],film['release_date'],film['original_language'],film['original_title'],
                          film['popularity']]


# create dataframe with film and revenue columns
df_2016.shape

(20, 10)

In [31]:
# for 2015
url_2015 = f'https://api.themoviedb.org/3/discover/movie?api_key={ds_key_1}&primary_release_year=2015&sort_by=revenue.desc'

In [32]:
ds_r_2015 = requests.get(url_2015)

df_2015 = pd.DataFrame.from_dict(ds_r_2015.json()['results'])
# print(len(df_2015)) #Print how many rows
# print(df_2015.columns) #Print column names
# df_2015

In [33]:
highest_revenue_2015 = ds_r_2015.json()

highest_revenue_films_2015 = highest_revenue_2015['results']

In [34]:
columns_2015 = ['id','film', 'revenue','genres','vote_count','vote_average','release_date','original_language',
           'orijinal_title','popularity']


# create dataframe with film and revenue columns
df_2015= pd.DataFrame(columns=columns_2015)

In [35]:
for film in highest_revenue_films_2015:
    # print(film['title'])
    film_revenue_2015 = requests.get('https://api.themoviedb.org/3/movie/'+ str(film['id']) +'?api_key='+ ds_key_1+'&language=en-US')
    film_revenue_2015 = film_revenue_2015.json()
    #print(locale.currency(film_revenue['revenue'], grouping=True ))
    df_2015.loc[len(df_2015)]=[film['id'],film['title'],film_revenue_2015['revenue'],film['genre_ids'],film['vote_count'],
                         film['vote_average'],film['release_date'],film['original_language'],film['original_title'],
                          film['popularity']]


# create dataframe with film and revenue columns
df_2015.shape

(20, 10)

In [36]:
# merging 5 years all data
to_concat = [df_1, df_2018, df_2017,df_2016,df_2015]
combined_df = pd.concat(to_concat)

In [37]:
combined_df.shape

(100, 10)

In [42]:
combined_df.reset_index()

,index,id,film,revenue,genres,vote_count,vote_average,release_date,original_language,orijinal_title,popularity
0,0,299534,Avengers: Endgame,2797800564,"[28, 12, 878]",11378,8.3,2019-04-24,en,Avengers: Endgame,39.839
1,1,420818,The Lion King,1656943394,"[12, 10751]",4577,7.1,2019-07-12,en,The Lion King,47.264
2,2,330457,Frozen II,1330764959,"[12, 16, 10751]",2591,7,2019-11-20,en,Frozen II,127.227
3,3,429617,Spider-Man: Far from Home,1131450163,"[28, 12, 878]",6121,7.5,2019-06-28,en,Spider-Man: Far from Home,52.388
4,4,299537,Captain Marvel,1128274794,"[28, 12, 878]",8387,7,2019-03-06,en,Captain Marvel,40.323
...,...,...,...,...,...,...,...,...,...,...,...
95,15,254128,San Andreas,470490832,"[28, 18, 53]",5636,6.1,2015-05-27,en,San Andreas,30.332
96,16,87101,Terminator Genisys,440603537,"[878, 28, 53, 12]",5841,5.9,2015-06-23,en,Terminator Genisys,45.374
97,17,76341,Mad Max: Fury Road,378858340,"[28, 12, 878]",15697,7.5,2015-05-13,en,Mad Max: Fury Road,20.357
98,18,228161,Home,368871007,"[16, 35, 14, 878, 10751]",2598,6.8,2015-03-18,en,Home,14.350
99,19,105864,The Good Dinosaur,331926147,"[12, 16, 10751]",3491,6.7,2015-11-14,en,The Good Dinosaur,18.998

In [48]:
combined_df.to_csv('movies.csv')

In [43]:
combined_df.head(30)

,id,film,revenue,genres,vote_count,vote_average,release_date,original_language,orijinal_title,popularity
0,299534,Avengers: Endgame,2797800564,"[28, 12, 878]",11378,8.3,2019-04-24,en,Avengers: Endgame,39.839
1,420818,The Lion King,1656943394,"[12, 10751]",4577,7.1,2019-07-12,en,The Lion King,47.264
2,330457,Frozen II,1330764959,"[12, 16, 10751]",2591,7,2019-11-20,en,Frozen II,127.227
3,429617,Spider-Man: Far from Home,1131450163,"[28, 12, 878]",6121,7.5,2019-06-28,en,Spider-Man: Far from Home,52.388
4,299537,Captain Marvel,1128274794,"[28, 12, 878]",8387,7,2019-03-06,en,Captain Marvel,40.323
5,475557,Joker,1073698955,"[80, 18, 53]",9521,8.2,2019-10-02,en,Joker,98.211
6,301528,Toy Story 4,1073394593,"[12, 16, 35, 14, 10751]",3771,7.5,2019-06-19,en,Toy Story 4,34.046
7,181812,Star Wars: The Rise of Skywalker,1058056021,"[28, 12, 878]",3051,6.5,2019-12-18,en,Star Wars: The Rise of Skywalker,54.990
8,420817,Aladdin,1047612394,"[12, 35, 14, 10749, 10751]",4927,7,2019-05-22,en,Aladdin,48.212
9,384018,Fast & Furious Presents: Hobbs & Shaw,760098996,"[28, 12, 35]",2620,6.6,2019-08-01,en,Fast & Furious Presents: Hobbs & Shaw,42.665
10,615453,Ne Zha,686067000,"[16, 35, 14]",30,7.4,2019-07-26,zh,哪吒之魔童降世,23.493
11,166428,How to Train Your Dragon: The Hidden World,517526875,"[12, 16, 10751]",3086,7.7,2019-01-03,en,How to Train Your Dragon: The Hidden World,34.495
12,420809,Maleficent: Mistress of Evil,491570967,"[12, 14, 10751]",1961,7.2,2019-10-16,en,Maleficent: Mistress of Evil,51.865
13,474350,It Chapter Two,472093228,"[18, 14, 27]",3245,6.8,2019-09-04,en,It Chapter Two,33.304
14,447404,Pokémon Detective Pikachu,431605346,"[28, 12, 14]",3248,6.9,2019-05-03,en,Pokémon Detective Pikachu,32.167
15,399579,Alita: Battle Angel,404852543,"[28, 12, 878, 53]",4329,6.9,2019-01-31,en,Alita: Battle Angel,35.214
16,373571,Godzilla: King of the Monsters,385900138,"[878, 28]",2107,6.2,2019-05-29,en,Godzilla: King of the Monsters,32.712
17,466272,Once Upon a Time… in Hollywood,374251247,"[35, 18, 53]",4841,7.5,2019-07-25,en,Once Upon a Time… in Hollywood,55.335
18,287947,Shazam!,363533271,"[28, 35, 14]",4374,7,2019-03-29,en,Shazam!,30.909
19,458156,John Wick: Chapter 3 - Parabellum,326699296,"[28, 80, 53]",3943,7.1,2019-05-15,en,John Wick: Chapter 3 - Parabellum,44.085
0,299536,Avengers: Infinity War,2046239637,"[28, 12, 878]",16888,8.3,2018-04-25,en,Avengers: Infinity War,83.956
1,284054,Black Panther,1346739107,"[28, 12, 14, 878]",14330,7.4,2018-02-13,en,Black Panther,34.973
2,351286,Jurassic World: Fallen Kingdom,1303459585,"[28, 12, 878]",6975,6.5,2018-06-06,en,Jurassic World: Fallen Kingdom,26.156
3,260513,Incredibles 2,1241891456,"[28, 12, 16, 10751]",7708,7.5,2018-06-14,en,Incredibles 2,28.622
4,297802,Aquaman,1143689193,"[28, 12, 14]",7978,6.8,2018-12-07,en,Aquaman,26.315
5,517141,In The Mood For Surrealism or 8021,1000000000,"[28, 18, 35, 99]",0,0,2018-04-24,en,In The Mood For Surrealism or 8021,0.600
6,424694,Bohemian Rhapsody,894027543,"[18, 10402]",10027,8,2018-10-24,en,Bohemian Rhapsody,32.503
7,335983,Venom,855013954,"[28, 878]",8013,6.6,2018-09-28,en,Venom,27.318
8,353081,Mission: Impossible - Fallout,791017452,"[28, 12]",4646,7.3,2018-07-13,en,Mission: Impossible - Fallout,29.138
9,383498,Deadpool 2,741547413,"[28, 12, 35]",10474,7.5,2018-05-10,en,Deadpool 2,30.757

In [39]:
url_genres = f'https://api.themoviedb.org/3/genre/movie/list?api_key={ds_key_1}&language=en-US' 
# To learn id_code of genres

In [40]:
ds_genres = requests.get(url_genres)

In [41]:
# List of genres

df_genres = pd.DataFrame.from_dict(ds_genres.json()['genres'])
print(len(df_genres)) #Print how many rows
print(df_genres.columns) #Print column names

df_genres

19
Index(['id', 'name'], dtype='object')

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [49]:
df_genres.to_csv('genre_codes.csv')